export declare type EmptyDescription = {};
export declare type Ngram = string;
export declare type Position = number;
export declare type Term = string;
export declare type Indexable = string | number | symbol;
export declare type Description = Map<Indexable, Position[]> | EmptyDescription;
export declare type StringDescription = Record<string, Position[]>;
export declare type NgramIndex = Map<Ngram, Description>;
export declare const empty: EmptyDescription;
export declare const nil: Position[];
