name: Docs

on:
  push:
    branches: [main]

jobs:
  all:
    name: all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          # cache: pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Pnpm install
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.x
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, typedoc, typescript]

      - name: Generate documentation
        run: pnpm run doc

      - name: Publish Docs
        run: |
          set -x
          git config user.name "Peter Hillerström"
          git config user.email "peter.hillerstrom@gmail.com"
          git add -f docs
          git status
          git commit -m "Update docs"
          git subtree split --prefix docs --branch gh-pages
          git push --force origin gh-pages:gh-pages
