name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['20.x', '21.x', '22.x']
        os:
            - ubuntu-latest
            # - macOS-latest
            # - windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          # cache: pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ matrix.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Pnpm install
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.x
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, typedoc, typescript]

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      # - name: Test
      #   run: pnpm test -- --check-coverage

      - name: Test & code coverage
        uses: paambaati/codeclimate-action@v2.7.1
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm coverage
