name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x']
        os:
            - ubuntu-latest
            # - macOS-latest
            # - windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node }}
          # cache: pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ matrix.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Pnpm install
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.10.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, typedoc, typescript]

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      # - name: Test
      #   run: pnpm test -- --check-coverage

      - name: Test & code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm coverage
