name: size
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Size limit
        uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.SIZE_LIMIT_GITHUB_TOKEN }}
          package_manager: pnpm
