name: size
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          # cache: pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Pnpm install
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.x

      - name: Size limit
        uses: andresz1/size-limit-action@v1.8.0
        with:
          github_token: ${{ secrets.SIZE_LIMIT_GITHUB_TOKEN }}
          package_manager: pnpm
